### ISSUE TITLE
Machine wide installation / user configuration / central policies

### ISSUE THREAD

**Issue by dnnnp** [WinSSHTerm/WinSSHTerm#19]
Hello friend,

I just discovered WinSSHTerm today and I love it so far, the interface is clean and beautiful and it provides exactly the features that I need. Thank you so much for all the work you do!

I have a question though: Is it possible to install WinSSHTerm to C:\Program Files? I seem to have issues with it because the directory is not writeable by regular users. Is there a way to tell WinSSHTerm to store it's configuration to %APPDATA% somehow? 

A second question I got: Is there a way for centralized management? An idea I got would be to implement configuration via Group Policy - for instance to set the central location for the shared connections file (beautiful feature btw!).

Any help would be greatly appreciated. If I can assist you in any matter (e.g. testing or helping develop admx files if you are actually interested in supporting Windows Group Policy), feel free to contact me.

Best regards
Daniel

**Comment by WinSSHTerm** [comment]
Hi, thanks for your feedback

If you install WinSSHTerm via msi package, the default installation path is "%LocalAppData%\Programs\WinSSHTerm". However, you can install it also to C:\Program Files (system wide). Please see point 30 in the [faq section](https://winsshterm.blogspot.com/p/faq_10.html). In both cases, the user configuration will be inside the "My Documents" directory.

There was recently added support for environment variables (point 32 in the [faq section](https://winsshterm.blogspot.com/p/faq_10.html)) to set the path for the client software like PuTTY centrally for all users. Would environment variables work for you?

**Comment by dnnnp** [comment]
Hi, thank you for your quick response.

You pointed me to the right direction, i managed to install all required components using a Powershell script. It's working file and I'm having no issues so far.

For my personal preference it would be nice to have the settings within the registry or even better support for group policies, so I could set everything up centrally managed, but this will work just fine. Thank you for your help and have a nice day!

Here's the Powershell Script, if anyone is interested (you need to create a folder "pkg" next to the script and place all the required installers within: Putty, WinSCP and WinSSHTerm as MSI File, VcXsrv as .exe file).

```powershell
$global:puttyInstaller = ""
$global:winscpInstaller = ""
$global:vcxsrvInstaller = ""
$global:winsshtermInstaller = ""

function Test-AdminPrivileges {
    Write-Output "Test if script is run as admin..."
    $currentPrincipal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
    if (-not $currentPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
        throw "Script is not running with administrative privileges."
    }
    Write-Output "OK"
}

function Get-InstallerPaths {
    Write-Output "Get full paths for installer files..."
    $global:puttyInstaller = ((Get-ChildItem (Join-Path $PSScriptRoot "pkg")) | Where-Object { $_.Name -Match "^putty-.*\.msi$" }).FullName
    $global:winscpInstaller = ((Get-ChildItem (Join-Path $PSScriptRoot "pkg")) | Where-Object { $_.Name -Match "^WinSCP-.*\.msi$" }).FullName
    $global:vcxsrvInstaller = ((Get-ChildItem (Join-Path $PSScriptRoot "pkg")) | Where-Object { $_.Name -Match "^vcxsrv-.*\.exe$" }).FullName
    $global:winsshtermInstaller = ((Get-ChildItem (Join-Path $PSScriptRoot "pkg")) | Where-Object { $_.Name -Match "^WinSSHTerm-.*\.msi$" }).FullName
    Write-Output "OK"
}

function Test-InstallerPaths {
    Write-Output "Test, if installer paths exist..."
    If(-Not $global:puttyInstaller -Or -Not (Test-Path $global:puttyInstaller)) {
        throw [System.IO.FileNotFoundException] "Putty installer not found."
    }
    If(-Not $global:winscpInstaller -Or -Not (Test-Path $global:winscpInstaller)) {
        throw [System.IO.FileNotFoundException] "WinSCP installer not found."
    }
    If(-Not $global:vcxsrvInstaller -Or -Not (Test-Path $global:vcxsrvInstaller)) {
        throw [System.IO.FileNotFoundException] "VCXSrv installer not found."
    }
    If(-Not $global:winsshtermInstaller -Or -Not (Test-Path $global:winsshtermInstaller)) {
        throw [System.IO.FileNotFoundException] "WinSSHTerm installer not found."
    }
    Write-Output "OK"
}

function Install-Putty {
    Write-Output "Installing PuTTY..."

    $arguments = "/i `"$global:puttyInstaller`" /quiet /norestart ALLUSERS=1"

    $process = Start-Process msiexec.exe -ArgumentList $arguments -Wait -PassThru

    if ($process.ExitCode -ne 0) {
        throw "PuTTY installation failed with exit code $($process.ExitCode)."
    }

    Write-Output "OK"
}

function Install-WinSCP {
    Write-Output "Installing WinSCP..."

    $arguments = "/i `"$global:winscpInstaller`" /quiet /norestart ALLUSERS=1"

    $process = Start-Process msiexec.exe -ArgumentList $arguments -Wait -PassThru

    if ($process.ExitCode -ne 0) {
        throw "WinSCP installation failed with exit code $($process.ExitCode)."
    }

    Write-Output "OK"
}

function Install-VCXSrv {
    Write-Output "Installing VCXSrv..."

    $arguments = "/S"

    $process = Start-Process "$global:vcxsrvInstaller" -ArgumentList $arguments -Wait -PassThru

    if ($process.ExitCode -ne 0) {
        throw "VCXSrv installation failed with exit code $($process.ExitCode)."
    }

    Write-Output "OK"
}

function Install-WinSSHTerm {
    Write-Output "Installing WinSSHTerm..."

    $arguments = "/i `"$global:winsshtermInstaller`" /quiet /norestart MSIINSTALLPERUSER=`"`""

    $process = Start-Process msiexec.exe -ArgumentList $arguments -Wait -PassThru

    if ($process.ExitCode -ne 0) {
        throw "WinSSHTerm installation failed with exit code $($process.ExitCode)."
    }

    Write-Output "OK"
}

function Set-WinSSHTermEnvironment {
    Write-Output "Setting up environment variables..."
    [System.Environment]::SetEnvironmentVariable('WINSSHTERM_TERMINAL_CUSTOM_PUTTY_LOCATION',(Join-Path ${env:ProgramFiles} "PuTTY\putty.exe"), 'Machine')
    [System.Environment]::SetEnvironmentVariable('WINSSHTERM_PAGEANT_CUSTOM_LOCATION',(Join-Path ${env:ProgramFiles} "PuTTY\pageant.exe"), 'Machine')
    [System.Environment]::SetEnvironmentVariable('WINSSHTERM_JUMP_SERVER_CUSTOM_PLINK_LOCATION',(Join-Path ${env:ProgramFiles} "PuTTY\plink.exe"), 'Machine')
    [System.Environment]::SetEnvironmentVariable('WINSSHTERM_COPY_FILES_CUSTOM_WINSCP_LOCATION',(Join-Path ${env:ProgramFiles(x86)} "WinSCP\WinSCP.exe"), 'Machine')
    [System.Environment]::SetEnvironmentVariable('WINSSHTERM_X_SERVER_CUSTOM_VCXSRV_LOCATION',(Join-Path ${env:ProgramFiles} "VcXsrv\vcxsrv.exe"), 'Machine')
    Write-Output "OK"
}

try {
    Test-AdminPrivileges
    Get-InstallerPaths
    Test-InstallerPaths

    Install-Putty
    Install-WinSCP
    Install-VCXSrv
    Install-WinSSHTerm
    Set-WinSSHTermEnvironment
}
catch {
    Write-Output "ERROR: $PSItem"
}
```

**Comment by dnnnp** [comment]
Working fine via MSI file and environment variables, as stated on the website / faq. Thank you for your help.

**Comment by WinSSHTerm** [comment]
Great, thanks for testing and for sharing your script! I will test the script it when I have time

I'm not the maintainer of the WinGet package. But thanks for the info, I'll look into it.

**Comment by WinSSHTerm** [comment]
Not sure why this fails
`winget install P-StSoftware.WinSSHTerm --scope machine`

However, this seem to work
`winget install P-StSoftware.WinSSHTerm --custom MSIINSTALLPERUSER=""`

**Comment by dnnnp** [comment]
I've been doing some digging but I'm still not sure where exactly the issue is. It may not be linked to the msi file at all. I downloaded the manifest from: https://cdn.winget.microsoft.com/cache/manifests/p/P-StSoftware/WinSSHTerm/2.35.2/8aad

And enabled support for local manifest files:
`winget settings --enable LocalManifestFiles`

After that I tried a machine wide installation using the manifest file:
`winget install --scope machine -m .\winsshterm.yaml --verbose`
--> Produces the same error for me.

Changing the installer in winsshterm.yaml to:
```
- Architecture: x64
  InstallerSha256: AECD63F7B3DFE01A4835DFC1E03F805A5B0CA5097493C42257FC8DC71CFBD6D6
  InstallerUrl: https://github.com/WinSSHTerm/WinSSHTerm/releases/download/2.35.2/WinSSHTerm-2.35.2-x64.msi
  ProductCode: '{DF8B8C73-6117-49A8-8B92-A606121AB737}'
  Scope: machine
```
and running `winget install --scope machine -m .\winsshterm.yaml --verbose` does get rid of the error, but still performs a user scope installation (weird!).

Checking the log files (`winget --logs`) reveals that `Property(S): MSIINSTALLPERUSER = 1` is set during MSI install.

Next thing I tried was modifying the manifest file further (basically I copied the the installer-secion and added one for each scope adding custom install switches). This seems to work as intended. Maybe winget isn't capable of setting paramters for MSI files automatically?

Here is the modified manifest file:
```
Author: P-St Software
Copyright: "Copyright \xA9 2015-22 P-St Software"
CopyrightUrl: https://winsshterm.blogspot.com/p/license.html
InstallerLocale: en-US
InstallerType: wix
Installers:
- Architecture: x64
  InstallerSha256: AECD63F7B3DFE01A4835DFC1E03F805A5B0CA5097493C42257FC8DC71CFBD6D6
  InstallerUrl: https://github.com/WinSSHTerm/WinSSHTerm/releases/download/2.35.2/WinSSHTerm-2.35.2-x64.msi
  ProductCode: '{DF8B8C73-6117-49A8-8B92-A606121AB737}'
  Scope: user
- Architecture: x64
  InstallerSha256: AECD63F7B3DFE01A4835DFC1E03F805A5B0CA5097493C42257FC8DC71CFBD6D6
  InstallerUrl: https://github.com/WinSSHTerm/WinSSHTerm/releases/download/2.35.2/WinSSHTerm-2.35.2-x64.msi
  ProductCode: '{DF8B8C73-6117-49A8-8B92-A606121AB737}'
  Scope: machine
  InstallerSwitches: 
     Custom: MSIINSTALLPERUSER=""
- Architecture: arm64
  InstallerSha256: 215B179049D95269C7323F49F7DC52EBB1BD391BD2DBC5462856D61DDA191FAF
  InstallerUrl: https://github.com/WinSSHTerm/WinSSHTerm/releases/download/2.35.2/WinSSHTerm-2.35.2-arm64.msi
  ProductCode: '{0D7B48C9-7D70-4842-AAD1-A3450F28325B}'
  Scope: user
- Architecture: arm64
  InstallerSha256: 215B179049D95269C7323F49F7DC52EBB1BD391BD2DBC5462856D61DDA191FAF
  InstallerUrl: https://github.com/WinSSHTerm/WinSSHTerm/releases/download/2.35.2/WinSSHTerm-2.35.2-arm64.msi
  ProductCode: '{0D7B48C9-7D70-4842-AAD1-A3450F28325B}'
  Scope: machine
  InstallerSwitches: 
     Custom: MSIINSTALLPERUSER=""
License: Freeware
LicenseUrl: https://winsshterm.blogspot.com/p/license.html
ManifestType: merged
ManifestVersion: 1.6.0
PackageIdentifier: P-StSoftware.WinSSHTerm
PackageLocale: en-US
PackageName: WinSSHTerm
PackageUrl: https://winsshterm.blogspot.com/
PackageVersion: 2.35.2
PrivacyUrl: https://winsshterm.blogspot.com/p/privacy-policy.html
Publisher: P-St Software
PublisherSupportUrl: http://winsshterm.blogspot.com/p/faq_10.html
PublisherUrl: https://winsshterm.blogspot.com/
ReleaseDate: 2024-05-30
ReleaseNotes: '- Bug fix: If a backup is created when a shared connection file is
  loaded, the local connections will be missing in the backup. Please recreate your
  backup with 2.35.2 or later, if it was created with 2.35.1 or earlier

  - Bug fix: Restoring a backup when a shared connection file is configured can cause
  an error and prevent WinSSHTerm from starting'
ReleaseNotesUrl: https://github.com/WinSSHTerm/WinSSHTerm/releases/tag/2.35.2
ShortDescription: A tabbed SSH solution for Windows, combining PuTTY, WinSCP and VcXsrv

```
